//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewspaperRuler.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewspaperRuler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Approved {
            get {
                object obj = ResourceManager.GetObject("Approved", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Content:
        ///	Правительство стартовало глобальную общественно-политическую Перестройку, в ходе которой пообещали увеличить количество рабочих мест более чем в 2 раза!.
        /// </summary>
        internal static string Article1_1 {
            get {
                return ResourceManager.GetString("Article1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 2
        ///Content:
        ///	Фестиваль света уже скоро! 31 сентября на главной площади столицы традиционно состоится одно из самых знаменательных событий страны – фестиваль света: тысячи лампочек будут зажжены в центре города.
        ///	Из них будут созданы рисунки и картины, которые оценят даже самые искушённые ценители красоты. Да-да, послевоенное время не станет помехой для проведения традиционного праздника. Следите за нам в новостях!
        ///.
        /// </summary>
        internal static string Article1_10 {
            get {
                return ResourceManager.GetString("Article1_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Reprimand: 1
        ///Mistake: PessimisticArticle
        ///Content:
        ///	Огромная часть населения страны голодает из-за отсутствия средств на проживание. Зарегистрированы первые летальные исходы..
        /// </summary>
        internal static string Article1_2 {
            get {
                return ResourceManager.GetString("Article1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Reprimand: 1
        ///Mistake: PessimisticArticle
        ///Content:
        ///	В северо-восточном районе страны погиб весь урожай кукурузы вследствие внезапных заморозков. Температура воздуха упала до -17°C..
        /// </summary>
        internal static string Article1_3 {
            get {
                return ResourceManager.GetString("Article1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 2
        ///Content:
        ///	Прогноз погоды: ожидается облачная погода с редкими просветами солнца, температура воздуха поднимется до +7°C..
        /// </summary>
        internal static string Article1_4 {
            get {
                return ResourceManager.GetString("Article1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Reprimand: 1
        ///Mistake: PessimisticArticle
        ///Content:
        ///	В ходе Перестройки планируется урезать права церкви. Священники требует невмешательства правительства в церковную сферу. Разгорелся скандал..
        /// </summary>
        internal static string Article1_5 {
            get {
                return ResourceManager.GetString("Article1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Reprimand: 1
        ///Mistake: PessimisticArticle
        ///Content:
        ///	Министерство въезда закроет восточную границу из-за локальных конфликтов со странами Андиплантийской коалиции..
        /// </summary>
        internal static string Article1_6 {
            get {
                return ResourceManager.GetString("Article1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Flag: ArticleAboutChampionWasApproved
        ///Content:
        ///	Прославленная олимпийская чемпионка Галина Руш беременна и скоро станет мамой. Поддержим её решительные действия!.
        /// </summary>
        internal static string Article1_7 {
            get {
                return ResourceManager.GetString("Article1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Content:
        ///	В ходе войны научный прогресс не стоял на месте. Учёные разработали новое мощнейшее оружие массового поражения, которое должно помочь защитить страну от очередных внеплановых вторжений. Министерство безопасности уверяет: гражданам нечего бояться..
        /// </summary>
        internal static string Article1_8 {
            get {
                return ResourceManager.GetString("Article1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Reprimand: 1
        ///Mistake: PessimisticArticle
        ///Content:
        ///	Безопасность страны под серьёзной угрозой: прошедшая война опустошила практически все резервы государства, а страны-агрессоры вольны вновь переступить черту в любой момент..
        /// </summary>
        internal static string Article1_9 {
            get {
                return ResourceManager.GetString("Article1_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Reprimand: 1
        ///Flag: ArticleOnMassStarvationWasApproved
        ///Mistake: PessimisticArticle
        ///Title: Безработица убивает
        ///Content:
        ///	Массовый голод из-за отсутствия достаточного количества рабочих мест продолжается. Чиновники отказываются комментировать происходящее..
        /// </summary>
        internal static string Article2_1 {
            get {
                return ResourceManager.GetString("Article2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Reprimand: 1
        ///Mistake: PessimisticArticle
        ///Flag: ArticleOnProhibitionWeaponsWasApproved
        ///Title: Научные достижения не помогут защитить страну
        ///Content:
        ///	Новое оружие массового поражения, предназначенное для защиты страны от внешних агрессоров, было отправлено в Международную ассоциацию мировой безопасности &quot;Апостол&quot; (МАМБА) на утверждение.
        ///	МАМБА дала запрет на использование оружия из-за его сильной разрушительной силы..
        /// </summary>
        internal static string Article2_10 {
            get {
                return ResourceManager.GetString("Article2_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 2
        ///Title: Фестиваль света
        ///Content:
        ///	Подготовка к фестивалю идёт полным ходом. Каждый гражданин может внести свой вклад в организацию главного мероприятия. Мы ждём вас на главной площади: любая помощь не помешает!
        ///	Фестиваль состоится через 2 дня..
        /// </summary>
        internal static string Article2_11 {
            get {
                return ResourceManager.GetString("Article2_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 2
        ///Title: Прогноз погоды в Уинбурге
        ///Content:
        ///	Ожидаются сильные осадки и ветер, температура воздуха опустится до -3°C..
        /// </summary>
        internal static string Article2_2 {
            get {
                return ResourceManager.GetString("Article2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Title: Осторожно, лёд!
        ///Content:
        ///	В северных районах страны после сходов горного снега и вследствие наступившей оттепели начался гололёд.
        ///	Гражданам следует быть осторожными, выходя на улицу..
        /// </summary>
        internal static string Article2_3 {
            get {
                return ResourceManager.GetString("Article2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Reprimand: 1
        ///Mistake: PessimisticArticle
        ///Title: Война или мир?
        ///Content:
        ///	Угроза очередного вторжения войск стран Андиплантийской коалиции с востока усиливается. Министерство безопасности уверяет, что всё под контролем..
        /// </summary>
        internal static string Article2_4 {
            get {
                return ResourceManager.GetString("Article2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Reprimand: 1
        ///Mistake: PessimisticArticle
        ///Flag: ArticleAboutSalaryDelayWasApproved
        ///Title: Зарплата снова опаздывает
        ///Content:
        ///	В Плиувиле рабочим трижды задержали заработную плату.
        ///	Люди грозятся забросать камнями здание администрации Плиувиля, если им не вернут обещанное жалованье за непрерывный труд..
        /// </summary>
        internal static string Article2_5 {
            get {
                return ResourceManager.GetString("Article2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Mistake: NoTitle
        ///Content:
        ///	Слава волонтёрам! Группа энтузиастов почистила и привела в порядок памятник военному руководителю Р. Г. Нескомову на главной площади столицы.
        ///	Этот памятник не реставрировался со времён начала войны..
        /// </summary>
        internal static string Article2_6 {
            get {
                return ResourceManager.GetString("Article2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Flag: ArticleOnDryRationsWasApproved
        ///Title: Скажем голоду нет!
        ///Content:
        ///	Государство выделит средства на закуп индивидуальных рационов питания, сухих пайков, в расчёте на каждого гражданина страны..
        /// </summary>
        internal static string Article2_7 {
            get {
                return ResourceManager.GetString("Article2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 2
        ///Title: Буря близ южных побережий
        ///Content:
        ///	Близ южной морской границы фиксируются резкие перепады атмосферного давления, что может привести к образованию урагана.
        ///	Жителям прибрежных населённых пунктов следует быть готовыми к экстренной эвакуации..
        /// </summary>
        internal static string Article2_8 {
            get {
                return ResourceManager.GetString("Article2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Mistake: NoTitle
        ///Content:
        ///	Респонденты сообщают, что в северо-восточных районах страны четвёртую часть кукурузы всё-таки удалось спасти.
        ///	Собранный урожай будет распределён между гражданами, оставшихся без работы..
        /// </summary>
        internal static string Article2_9 {
            get {
                return ResourceManager.GetString("Article2_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Title: Cookies банкрот?
        ///Content:
        ///	Недавнее исследование независимой частной экспертизы по контролю качества продуктов выявило, что всеми любимое лакомство — сдобное печенье Cookies — содержит в себе токсичные вещества в незначительных количествах вследствие неоднократного нарушения технологии производства и условий хранения.
        ///	Компания Cookies, которая назвала печенье в свою честь, терпит огромные убытки..
        /// </summary>
        internal static string Article3_1 {
            get {
                return ResourceManager.GetString("Article3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Mistake: NoTitle
        ///Content:
        ///	Владелец частной аптеки &quot;Таблеточка&quot; приговорена к лишению свободы. Срок не сообщается, но ясно, что надолго.
        ///	Судя по показаниям очевидцев, она промышляла порошковыми запрещёнными веществами, продавая их под видом лекарства от головной боли..
        /// </summary>
        internal static string Article3_10 {
            get {
                return ResourceManager.GetString("Article3_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 2
        ///Title: Прогноз погоды в юго-восточных областях
        ///Content:
        ///	Поставщиком тёплого воздуха является циклон. Он штурмует юго-восточные границы, но этот тёплый воздух сопровождают осадки: будет сильные дожди.
        ///	Сегодня температура опустится до -6°С, зато завтра настанет оттепель..
        /// </summary>
        internal static string Article3_11 {
            get {
                return ResourceManager.GetString("Article3_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Mistake: NoTitle
        ///Content:
        ///	На главной площади столицы пройдёт ярмарка фермерских продуктов, выращенных гражданами собственноручно.
        ///	Администрация города дала разрешение на организацию данного мероприятия..
        /// </summary>
        internal static string Article3_12 {
            get {
                return ResourceManager.GetString("Article3_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Mistake: PremeditatedMurder
        ///Title: Происшествие у ТЦ &quot;Сатурн&quot;
        ///Content:
        ///	Тело 54-летней женщины обнаружили у торгового центра &quot;Сатурн&quot;.
        ///	Судя по всему, жертва была убита быстро и жестоко: на теле специалисты нашли по крайне мере 12 ножевых ранений.
        ///	На месте уже работает следственно-оперативная группа..
        /// </summary>
        internal static string Article3_13 {
            get {
                return ResourceManager.GetString("Article3_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 2
        ///Title: Перенос фестиваля света
        ///Content:
        ///	Вышел приказ о переносе фестиваля света на 1 октября. Как сообщает Министерство культуры, это связано с накопившимися финансовыми проблемами. Однако традиционный праздник всё же будет проведён, но с опозданием.
        ///	Фестиваль состоится через 2 дня.
        ///.
        /// </summary>
        internal static string Article3_14 {
            get {
                return ResourceManager.GetString("Article3_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 2
        ///Reprimand: 2
        ///Order: 2
        ///Flag: ArticleOnProhibitionWeaponsWasApproved
        ///Mistake: War
        ///Title: Наше будущее под угрозой?
        ///Content:
        ///	Несмотря на запрет МАМБА использовать новое оружие массового поражения, военное руководство вопреки этому планирует применить его близ восточной границы в борьбе со странами Андиплантийской коалиции..
        /// </summary>
        internal static string Article3_2 {
            get {
                return ResourceManager.GetString("Article3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Title: Безработица торжествует
        ///Content:
        ///	На вопрос о формировании новых рабочих мест в рамках Перестройки правительство дало ответ, что временно приостанавливает данный процесс. Причина неизвестна.
        ///	Такой поворот событий вызвал большое негодование среди граждан..
        /// </summary>
        internal static string Article3_3 {
            get {
                return ResourceManager.GetString("Article3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Reprimand: 1
        ///Mistake: War
        ///Title: Новая агрессия с севера
        ///Content:
        ///	Замечены военные лагеря Убрингстона близ северной границы страны.
        ///	Похоже, они не сдадутся, пока не отвоюют наше побережье Зелёного моря, которое даёт безграничные возможности для прокладывания морских торговых путей к большинству северным странам..
        /// </summary>
        internal static string Article3_4 {
            get {
                return ResourceManager.GetString("Article3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Reprimand: 1
        ///Mistake: War
        ///Title: Вас не забудем.
        ///Content:
        ///	Продолжающиеся военные конфликты близ восточной границы унесли жизни 289 человек..
        /// </summary>
        internal static string Article3_5 {
            get {
                return ResourceManager.GetString("Article3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Reprimand: 1
        ///Mistake: War
        ///Title: Новые поборы?
        ///Content:
        ///	На формирование новой армии ушли средства, которые составляли очередные внеплановые налоги с граждан.
        ///	У людей, не имевших денежных средств, изымали продукты питания и одежду.
        ///	Армия отправится на подкрепление в борьбе со странами Андиплантийской коалиции..
        /// </summary>
        internal static string Article3_6 {
            get {
                return ResourceManager.GetString("Article3_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Reprimand: 1
        ///Mistake: War
        ///Title: Безопасность страны — превыше всего
        ///Content:
        ///	Министерство безопасности старается удерживать агрессоров за чертой страны, однако военные конфликты только усиливаются.
        ///	Вероятно, именно это стало весомой причиной внеплановых поборов и затягивания с программой Перестройки..
        /// </summary>
        internal static string Article3_7 {
            get {
                return ResourceManager.GetString("Article3_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Reprimand: 1
        ///Mistake: War
        ///Title: Дефицит муки
        ///Content:
        ///	Доставка импортной муки в пункты продажи прекратилась в связи с дорогой, проходящей через горячую точку военных конфликтов близ восточной границы.
        ///	Покупатели в панике разбирают оставшуюся муку с полок магазинов.
        ///	Однако фирма &quot;Cake is Fake&quot; спешит всех успокоить: руководство компании планирует начало строительства фабрик по производству муки по всей стране. Закупочную цену товара пока не сообщают..
        /// </summary>
        internal static string Article3_8 {
            get {
                return ResourceManager.GetString("Article3_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Reprimand: 1
        ///Mistake: War
        ///Title: Философская дискуссия &quot;Привет из прошлого&quot;
        ///Content:
        ///	Почему именно наша страна находится под прицелом других стран? В чём причина военных конфликтов, не дающих нам спокойно жить уже на протяжении 5 лет? И есть ли вообще такая причина?
        ///	Может, мы им просто не нравимся?  А может, мы лишняя пешка на международной арене?
        ///	Обо всём этом поговорим в сегодняшней документально-исследовательской статье &quot;Привет из прошлого&quot;..
        /// </summary>
        internal static string Article3_9 {
            get {
                return ResourceManager.GetString("Article3_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 2
        ///Title: Фестиваль уже завтра!
        ///Content:
        ///	Традиционный фестиваль света уже на подходе! Граждане трудятся на площади не покладая рук: они желают сделать этот праздник незабываемым, несмотря на столь сложный период для страны.
        ///	
        ///	На этот раз благотворительный фонд производит сбор денег посредством продажи билетов, которые пойдут на формирование новых рабочих мест. Стоимость билета: 30 ТОКЕНОВ.
        ///
        ///	Фестиваль будет проведён завтра, 1 октября, на главной площади с 16:00 до 23:00..
        /// </summary>
        internal static string Article4_1 {
            get {
                return ResourceManager.GetString("Article4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Mistake: Future
        ///Reprimand: 1
        ///Title: Снайпер с балкона 5-этажного дома открыл огонь по пешеходам
        ///Content:
        ///	В столице по ул. Рождественская мужчина начал стрельбу по пешеходам с балкона 5-этажного дома. Судя по данным очевидцев, было госпитализировано 2 пострадавших. Снайпер пойман, дело осталось за решением суда. Данные от 6 октября 1987 года.
        ///.
        /// </summary>
        internal static string Article4_10 {
            get {
                return ResourceManager.GetString("Article4_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Title: Наводнение в северо-восточных районах
        ///Content:
        ///	Обильные дожди в северо-восточных районах страны стали причиной большого наводнения городов, в результате которого пострадало более 20 человек. Судя по всему, причиной наводнения также стала река Зевок, которая вышла с берегов. Данные от 30 сентября 1987 года.
        ///.
        /// </summary>
        internal static string Article4_11 {
            get {
                return ResourceManager.GetString("Article4_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Mistake: War
        ///Title: Военные конфликты обостряются
        ///Content:
        ///	Военные конфликты со странами Андиплантийской коалиции становятся более жёсткими. Похоже, государство намеревается заключить с ними мирный договор, отправив министра безопасности. Данные от 30 сентября 1987 года.
        ///.
        /// </summary>
        internal static string Article4_12 {
            get {
                return ResourceManager.GetString("Article4_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 2
        ///Title: Заморозки в южных областях
        ///Content:
        ///	По прогнозам синоптиков в южных областях страны ожидается понижение температуры с +14°C до -6°C. В этом году плюсовой температуры больше не будет.
        ///.
        /// </summary>
        internal static string Article4_13 {
            get {
                return ResourceManager.GetString("Article4_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Mistake: Deprecated
        ///Title: Новая школа в Плиувиле ждёт первых учеников
        ///Content:
        ///	Плиувильцы торжествуют, ведь для обучающихся открыта новая школа, которая начнёт свою историю с 4 мая 1982 года. Школа построена на месте руин бывшего стеклозаготовительного завода.
        ///.
        /// </summary>
        internal static string Article4_14 {
            get {
                return ResourceManager.GetString("Article4_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Order: 2
        ///Flag: AnnouncementOfDisappearanceOfGalinasHusbandWasApproved
        ///Mistake: MissingPerson
        ///Title: ОБЪЯВЛЕНИЕ О ПРОПАЖЕ
        ///Content:
        ///	В столице страны пропал муж известной олимпийской чемпионки Галины Руш, Виктор Руш. Приметы:
        ///
        ///	— Рост: 191 см.
        ///	— Глаза: карие.
        ///	— Внешний вид: чёрная кожаная куртка, серые брюки, татуировка на шее в виде змеи.
        ///
        ///	Последний раз был замечен в ресторане «Сосна» за столиком №3.
        ///
        ///	В случае обнаружения звоните агенту Галины Руш по телефону 29-324-01.
        ///
        ///.
        /// </summary>
        internal static string Article4_15 {
            get {
                return ResourceManager.GetString("Article4_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Title: Налажено почтовое сообщение
        ///Content:
        ///	Мы долго ждали, и это свершилось! Министерство финансов выделило средства на возобновление почтовой связи, которая была разорвана в начале войны на долгие годы.
        ///	
        ///	Теперь граждане могут отправлять не только письма или небольшую стопку документов, но и посылки больших размеров..
        /// </summary>
        internal static string Article4_2 {
            get {
                return ResourceManager.GetString("Article4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 2
        ///Title: Общий прогноз погоды
        ///Content:
        ///	При какой погоде начнётся октябрь? Под влиянием пониженного атмосферного давления на большей части территории страны пройдут дожди. Местами прогремят грозы. Ночью будет особенно прохладно, от -5 до -1 °С, а днём термометры покажут не выше +3°С..
        /// </summary>
        internal static string Article4_3 {
            get {
                return ResourceManager.GetString("Article4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Mistake: MissingPerson
        ///Flag: MissingPersonNoticeWasPublished
        ///Title: ОБЪЯВЛЕНИЕ
        ///Content:
        ///	В Плиувиле пропал мальчик, Геннадий, 13 лет. 29 сентября, в районе 19:30 сказал, что пошёл погулять с друзьями в сторону Капрастского пустыря, но домой он так и не вернулся. Рост 165 см, одет был в светлые джинсы и клетчатую красную рубашку.
        ///
        ///	СРОЧНО! Помогите его найти!.
        /// </summary>
        internal static string Article4_4 {
            get {
                return ResourceManager.GetString("Article4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Title: Новая коллекция одежды фирмы «Король моды»
        ///Content:
        ///	В магазины фирмы «Король моды» поступила новая коллекция модной сногсшибательной мужской одежды. Хотите удивить жену? Показать себя на свидании с лучшей стороны? Подчеркнуть свою идеальную фигуру и телосложение? Тогда Вам к нам!
        ///
        ///	Наиболее популярной в коллекции оказалась облегающая рубашка цвета морской волны «Bon Aquarelle» стоимостью 1400 ТОКЕНОВ. Ужасно низкие цены!
        ///
        ///	Наша фирма делает всё для комфортного времяпрепровождения  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Article4_5 {
            get {
                return ResourceManager.GetString("Article4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Mistake: Deprecated
        ///Reprimand: 1
        ///Title: Фестиваль света пройдёт в обычном режиме
        ///Content:
        ///	Традиционный фестиваль света назначен на 30 сентября 1982 год. Вход бесплатный! Все желающие граждане смогут лицезреть прекрасный ночной город, украшенный тысячами фонарей. Добро пожаловать!.
        /// </summary>
        internal static string Article4_6 {
            get {
                return ResourceManager.GetString("Article4_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Mistake: Future
        ///Reprimand: 1
        ///Title: Смертность от всеми известного вируса снижается
        ///Content:
        ///	По некоторым данным от 14 августа 1988 года мировая смертность от опаснейшей модификации бронхиальной астмы начала снижаться. Убрингстон – первая в мире страна, полностью избавившаяся от столь заразного вируса. Все границы временно закрыты как для въезда, так и для выезда..
        /// </summary>
        internal static string Article4_7 {
            get {
                return ResourceManager.GetString("Article4_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Title: Первые рабочие места
        ///Content:
        ///	Государственная программа Перестройки начала давать свои плоды! Первые рабочие места появились в Плиувиле. Их предоставили разгневанным рабочим, которые относительно недавно жаловались на отсутствие зарплат..
        /// </summary>
        internal static string Article4_8 {
            get {
                return ResourceManager.GetString("Article4_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Mistake: Deprecated
        ///Reprimand: 1
        ///Title: Воспламенение автобуса в Гординске
        ///Content:
        ///	12 июня 1987 года в Гординске на остановке «Перелётная» вспыхнул маршрутный автобус №410.
        ///
        ///	Об инциденте сообщили свидетели. Сначала автобус задымился, пассажиров успели эвакуировать. После транспортное средство загорелось, пламя перекинулось на остановку.
        ///
        ///	Огнем было охвачено 20 квадратных метров. Обошлось без пострадавших.
        ///.
        /// </summary>
        internal static string Article4_9 {
            get {
                return ResourceManager.GetString("Article4_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Mistake: PremeditatedMurder
        ///Title: Камень на шею, да ко дну
        ///Content:
        ///	Один из городов всколыхнула новость об убийстве дальнобойщика, доставлявшего продукты в столицу государства..
        /// </summary>
        internal static string Article5_1 {
            get {
                return ResourceManager.GetString("Article5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 2
        ///Mistake: War
        ///Title: По законам военного времени
        ///Content:
        ///	Состоялся суд над мародёрами, запятнавшими имя воина-защитника..
        /// </summary>
        internal static string Article5_2 {
            get {
                return ResourceManager.GetString("Article5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 2
        ///Title: А судьи кто?
        ///Content:
        ///	В средствах массовой информации разразился скандал, связанный с именем известного литератора. Причиной его стал выпуск новой книги о масштабах деятельности местной мафии..
        /// </summary>
        internal static string Article5_3 {
            get {
                return ResourceManager.GetString("Article5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 2
        ///Title: Вокруг света
        ///Content:
        ///	Наконец состоялся долгожданный фестиваль света. В столице государства зрителям были представлены новые технологии и искусство света. Отдельные территории превратились в парк чудес..
        /// </summary>
        internal static string Article5_4 {
            get {
                return ResourceManager.GetString("Article5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 2
        ///Title: Будет день, будет и рекорд
        ///Content:
        ///	В городе прошла презентация самого большого числа горелок, работающих одновременно. Организаторы надеются побить установленный рекорд..
        /// </summary>
        internal static string Article5_5 {
            get {
                return ResourceManager.GetString("Article5_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 2
        ///Mistake: Future
        ///Title: На вкус и свет товарищи есть
        ///Content:
        ///	3 октября состоялась премьера светомузыкального представления. Зрителей удивили визуальные эффекты, созданные под музыкальные композиции..
        /// </summary>
        internal static string Article5_6 {
            get {
                return ResourceManager.GetString("Article5_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Title: Не в деньгах счастье
        ///Content:
        ///	В стране зафиксирован заболевший неизвестным вирусом пациент. Им оказался по иронии самый богатый человек..
        /// </summary>
        internal static string Article5_7 {
            get {
                return ResourceManager.GetString("Article5_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Title: А вечер перестал быть томным…
        ///Content:
        ///	На светской вечеринке одному из гостей стало плохо. Все гости переполошились, выдвигая разные версии происшедшего и находя признаки новой инфекции..
        /// </summary>
        internal static string Article5_8 {
            get {
                return ResourceManager.GetString("Article5_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loyality: 1
        ///Mistake: NoTitle
        ///Content:
        ///	Напрасно просил упавший человек о помощи. Многолюдная прежде улица словно вымерла. Вот что делает с людьми страх заразиться новым неизведанным вирусом..
        /// </summary>
        internal static string Article5_9 {
            get {
                return ResourceManager.GetString("Article5_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream BeginLevel {
            get {
                return ResourceManager.GetStream("BeginLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Book {
            get {
                object obj = ResourceManager.GetObject("Book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Button {
            get {
                object obj = ResourceManager.GetObject("Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Cancel {
            get {
                return ResourceManager.GetStream("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ChooseOption {
            get {
                return ResourceManager.GetStream("ChooseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dead {
            get {
                object obj = ResourceManager.GetObject("Dead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № 34.10. Отклонять статьи пессимистического характера
        ///№ 34.11. Отклонять статьи без заголовка.
        /// </summary>
        internal static string DecreesLevel2 {
            get {
                return ResourceManager.GetString("DecreesLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № 34.11. Отклонять статьи без заголовка
        ///№ 34.12. Отклонять статьи с упоминаниями о войне
        ///№ 34.13. Отклонять статьи об умышленных убийствах.
        /// </summary>
        internal static string DecreesLevel3 {
            get {
                return ResourceManager.GetString("DecreesLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № 34.11. Отклонять статьи без заголовка
        ///№ 34.12. Отклонять статьи с упоминаниями о войне
        ///№ 34.13. Отклонять статьи об умышленных убийствах
        ///№ 34.14. Отклонять статьи с неактуальной информацией
        ///№ 34.15. Отклонять объявления о пропажах.
        /// </summary>
        internal static string DecreesLevel4 {
            get {
                return ResourceManager.GetString("DecreesLevel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № 34.11. Отклонять статьи без заголовка
        ///№ 34.12. Отклонять статьи с упоминаниями о войне
        ///№ 34.13. Отклонять статьи об умышленных убийствах
        ///№ 34.14. Отклонять статьи с неактуальной информацией
        ///№ 34.15. Отклонять объявления о пропажах
        ///№ 34.16. Отклонять рекламные объявления
        ///№ 34.17. Отклонять статьи о конкретных личностях.
        /// </summary>
        internal static string DecreesLevel5 {
            get {
                return ResourceManager.GetString("DecreesLevel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № 34.11. Отклонять статьи без заголовка
        ///№ 34.13. Отклонять статьи об умышленных убийствах
        ///№ 34.14. Отклонять статьи с неактуальной информацией
        ///№ 34.15. Отклонять объявления о пропажах
        ///№ 34.16. Отклонять рекламные объявления
        ///№ 34.17. Отклонять статьи о конкретных личностях
        ///№ 34.18. Отклонять статьи о вирусе КРАБ.
        /// </summary>
        internal static string DecreesLevel6 {
            get {
                return ResourceManager.GetString("DecreesLevel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № 34.11. Отклонять статьи без заголовка
        ///№ 34.14. Отклонять статьи с неактуальной информацией
        ///№ 34.15. Отклонять объявления о пропажах
        ///№ 34.16. Отклонять рекламные объявления
        ///№ 34.17. Отклонять статьи о конкретных личностях
        ///№ 34.18. Отклонять статьи о вирусе КРАБ
        ///№ 34.19. Отклонять статьи без направленности.
        /// </summary>
        internal static string DecreesLevel7 {
            get {
                return ResourceManager.GetString("DecreesLevel7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № 34.11. Отклонять статьи без заголовка
        ///№ 34.14. Отклонять статьи с неактуальной информацией
        ///№ 34.15. Отклонять объявления о пропажах
        ///№ 34.16. Отклонять рекламные объявления
        ///№ 34.17. Отклонять статьи о конкретных личностях
        ///№ 34.19. Отклонять статьи без направленности
        ///№ 34.20. Отклонять статьи о массовых протестах.
        /// </summary>
        internal static string DecreesLevel8 {
            get {
                return ResourceManager.GetString("DecreesLevel8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Error {
            get {
                return ResourceManager.GetStream("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Expired {
            get {
                object obj = ResourceManager.GetObject("Expired", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fired {
            get {
                object obj = ResourceManager.GetObject("Fired", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Font {
            get {
                object obj = ResourceManager.GetObject("Font", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frame {
            get {
                object obj = ResourceManager.GetObject("Frame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream GameOver {
            get {
                return ResourceManager.GetStream("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mail {
            get {
                object obj = ResourceManager.GetObject("Mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream MainMenu {
            get {
                return ResourceManager.GetStream("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Megaphone {
            get {
                object obj = ResourceManager.GetObject("Megaphone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MenuBackground {
            get {
                object obj = ResourceManager.GetObject("MenuBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream MenuButton {
            get {
                return ResourceManager.GetStream("MenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Money {
            get {
                return ResourceManager.GetStream("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Music {
            get {
                return ResourceManager.GetStream("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoteBackground1 {
            get {
                object obj = ResourceManager.GetObject("NoteBackground1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Notification {
            get {
                return ResourceManager.GetStream("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream PanelHide {
            get {
                return ResourceManager.GetStream("PanelHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream PanelShow {
            get {
                return ResourceManager.GetStream("PanelShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paper {
            get {
                object obj = ResourceManager.GetObject("Paper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Paper1 {
            get {
                return ResourceManager.GetStream("Paper1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Print {
            get {
                return ResourceManager.GetStream("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rejected {
            get {
                object obj = ResourceManager.GetObject("Rejected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RemarkBackground {
            get {
                object obj = ResourceManager.GetObject("RemarkBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream StampEnter {
            get {
                return ResourceManager.GetStream("StampEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream StampPut {
            get {
                return ResourceManager.GetStream("StampPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream StampReturn1 {
            get {
                return ResourceManager.GetStream("StampReturn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream StampReturn2 {
            get {
                return ResourceManager.GetStream("StampReturn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream StampTake1 {
            get {
                return ResourceManager.GetStream("StampTake1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream StampTake2 {
            get {
                return ResourceManager.GetStream("StampTake2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream StampTake3 {
            get {
                return ResourceManager.GetStream("StampTake3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream StampTake4 {
            get {
                return ResourceManager.GetStream("StampTake4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Suddenness {
            get {
                return ResourceManager.GetStream("Suddenness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SwitchOff {
            get {
                object obj = ResourceManager.GetObject("SwitchOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SwitchOn {
            get {
                object obj = ResourceManager.GetObject("SwitchOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.IO.UnmanagedMemoryStream, аналогичного System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Title {
            get {
                return ResourceManager.GetStream("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TrashCan {
            get {
                object obj = ResourceManager.GetObject("TrashCan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фестиваль света на главной площади
        ///Закон и правопорядок.
        /// </summary>
        internal static string TrendsLevel5 {
            get {
                return ResourceManager.GetString("TrendsLevel5", resourceCulture);
            }
        }
    }
}
